apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ds-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ds
    spec:
      containers:
      - name: ds-pod
        image: areynolds762/test-forgerock-ds
        imagePullPolicy: Always
        ports:
        - containerPort: 389
          name: ldap
        - containerPort: 4444
          name: admin